FROM python:3.7

WORKDIR /work

COPY . /work

COPY ./requirements.txt /work/requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt 

CMD ["gunicorn", "--bind", "0.0.0.0:5050", "app.app:app"]

EXPOSE 5050